[build]
  command = "sudo apt-get update && sudo apt-get install -y libmysqlclient-dev && bundle install && bundle exec rails db:migrate"
  publish = "public"

[build.environment]
  RUBY_VERSION = "3.1.2"